#pragma once

#define MAINS_RELAY_PIN 8

#define WATER_VALVE_RELAY 11
#define MILK_VALVE_RELAY 12
#define DRAINAGE_VALVE_RELAY 10
#define AIR_VALVE_RELAY 7

#define BOWL_STEPPER_DIR 2
#define BOWL_STEPPER_STEP 3
#define DISC_STEPPER_DIR 4
#define DISC_STEPPER_STEP 5
#define STEPS_PER_STEPPER_REVOLUTION 200

#define DRAINAGE_SERVO 9
#define DRAINAGE_REST_ANGLE 0
#define DRAINAGE_CONTACT_ANGLE 47

#define CAMERA_SERVO_PIN 6
#define CAMERA_OFF_ANGLE 106
#define CAMERA_ON_ANGLE 126
